# Generated by Django 6.0.4 on 2026-04-30 03:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('mascotas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('control', 'Control general'), ('vacunacion', 'Vacunación'), ('cirugia', 'Cirugía'), ('urgencia', 'Urgencia'), ('post_operatorio', 'Post-operatorio'), ('desparasitacion', 'Desparasitación'), ('otro', 'Otro')], default='control', max_length=30)),
                ('motivo_consulta', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, null=True)),
                ('proxima_visita', models.DateField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='mascotas.mascota')),
                ('turno', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_clinica', to='agenda.turno')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_clinicas', to='usuarios.veterinarioperfil')),
            ],
            options={
                'verbose_name': 'Consulta Clinica',
                'verbose_name_plural': 'Consultas Clinicas',
                'db_table': 'consultas_clinicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('medicamento', models.CharField(max_length=150)),
                ('dosis', models.CharField(max_length=150)),
                ('frecuencia', models.CharField(blank=True, max_length=150, null=True)),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='historia_clinica.consultaclinica')),
            ],
            options={
                'verbose_name': 'Item de Receta',
                'verbose_name_plural': 'Items de Receta',
                'db_table': 'receta_items',
                'ordering': ['consulta', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_proxima', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='mascotas.mascota')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunas_aplicadas', to='usuarios.veterinarioperfil')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'db_table': 'vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
