# Generated by Django 6.0.4 on 2026-05-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultaclinica',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='consultaclinica',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='recetaitem',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recetaitem',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='vacuna',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vacuna',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
    ]
