# Generated by Django 6.0.4 on 2026-05-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
    ]
