# Generated by Django 6.0.3 on 2026-04-15 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duración en minutos')),
            ],
            options={
                'db_table': 'servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='veterinaria.rol')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, null=True)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('peso_actual', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mascotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('control', 'Control general'), ('vacunacion', 'Vacunación'), ('cirugia', 'Cirugía'), ('urgencia', 'Urgencia'), ('post_operatorio', 'Post-operatorio'), ('desparasitacion', 'Desparasitación'), ('otro', 'Otro')], default='control', max_length=30)),
                ('motivo_consulta', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, null=True)),
                ('proxima_visita', models.DateField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='veterinaria.mascota')),
            ],
            options={
                'db_table': 'consultas_clinicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('turno', 'Turno'), ('vacuna', 'Vacuna'), ('internacion', 'Internación'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tamano', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('variable', 'Variable')], default='variable', max_length=20)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='razas', to='veterinaria.especie')),
            ],
            options={
                'db_table': 'razas',
                'ordering': ['nombre'],
                'unique_together': {('especie', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='veterinaria.raza'),
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('medicamento', models.CharField(max_length=150)),
                ('dosis', models.CharField(max_length=150)),
                ('frecuencia', models.CharField(blank=True, max_length=150, null=True)),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='veterinaria.consultaclinica')),
            ],
            options={
                'db_table': 'recetas_items',
                'ordering': ['consulta', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('en_espera', 'En espera'), ('en_consulta', 'En consulta'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('motivo_consulta', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_por_cliente', models.BooleanField(default=False)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='veterinaria.mascota')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='veterinaria.servicio')),
            ],
            options={
                'db_table': 'turnos',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_clinica', to='veterinaria.turno'),
        ),
        migrations.CreateModel(
            name='VeterinarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=120, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_veterinario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinarios_perfiles',
                'ordering': ['usuario__apellido', 'usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_proxima', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='veterinaria.mascota')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunas_aplicadas', to='veterinaria.veterinarioperfil')),
            ],
            options={
                'db_table': 'vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_asignados', to='veterinaria.veterinarioperfil'),
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('diagnostico_ingreso', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('internado', 'Internado'), ('observacion', 'En observación'), ('alta', 'Alta médica')], default='internado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internaciones', to='veterinaria.mascota')),
                ('veterinario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_responsable', to='veterinaria.veterinarioperfil')),
            ],
            options={
                'db_table': 'internaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='HorarioVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='veterinaria.veterinarioperfil')),
            ],
            options={
                'db_table': 'horarios_veterinarios',
                'ordering': ['veterinario', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionInternacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descripcion', models.TextField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='veterinaria.internacion')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones_internacion', to='veterinaria.veterinarioperfil')),
            ],
            options={
                'db_table': 'evoluciones_internacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_clinicas', to='veterinaria.veterinarioperfil'),
        ),
    ]
