# Generated by Django 6.0.4 on 2026-04-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raza',
            name='tamano',
        ),
    ]
