# Generated by Django 6.0.4 on 2026-05-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_fecha_creacion_horarioveterinario_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioveterinario',
            unique_together={('veterinario', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
