# Generated by Django 6.0.4 on 2026-05-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_horarioveterinario_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioveterinario',
            unique_together=set(),
        ),
    ]
