# Generated by Django 6.0.4 on 2026-04-30 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duracion en Minutos')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('en_espera', 'En espera'), ('en_consulta', 'En consulta'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='mascotas.mascota')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='agenda.servicio')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.veterinarioperfil')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
