# Generated by Django 6.0.4 on 2026-04-30 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='creado_por_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo_consulta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_asignados', to='usuarios.veterinarioperfil'),
        ),
    ]
