# Generated by Django 6.0.4 on 2026-05-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_rename_fecha_creacion_servicio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='urgencia',
            field=models.BooleanField(default=False),
        ),
    ]
