# Generated by Django 6.0.4 on 2026-04-30 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('diagnostico_ingreso', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('internado', 'Internado'), ('observacion', 'En observación'), ('alta', 'Alta médica')], default='internado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internaciones', to='mascotas.mascota')),
                ('veterinario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internaciones_responsable', to='usuarios.veterinarioperfil')),
            ],
            options={
                'verbose_name': 'Internación',
                'verbose_name_plural': 'Internaciones',
                'db_table': 'internaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionInternacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descripcion', models.TextField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones_internacion', to='usuarios.veterinarioperfil')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='internaciones.internacion')),
            ],
            options={
                'verbose_name': 'Evolución de Internación',
                'verbose_name_plural': 'Evoluciones de Internación',
                'db_table': 'evoluciones_internacion',
                'ordering': ['-fecha'],
            },
        ),
    ]
