# Generated by Django 6.0.4 on 2026-04-30 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='mascotas.especie')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'db_table': 'razas',
                'ordering': ['especie__nombre', 'nombre'],
                'unique_together': {('especie', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='mascotas.raza')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascotas',
                'ordering': ['nombre'],
            },
        ),
    ]
